version: "3"
services:
  mysql:
    image: fantabulous/mysql:latest
    build: mysql
  redis-sessions:
    image: fantabulous/redis:cache
    build:
      context: redis
      dockerfile: Dockerfile.Cache
  redis-users:
    image: fantabulous/redis:cache
  api-users:
    image: fantabulous/api:users
    build:
      context: dotnet
      args:
        app: Api.Users
    environment:
      ASPNETCORE_ENVIRONMENT: Test
  ui-react:
    image: fantabulous/react:latest
    build: react
  proxy:
    image: fantabulous/proxy:latest
    build: proxy
    ports:
      - "80:80"
